# Generated by Django 3.1.7 on 2021-03-04 16:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Buyer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField()),
                ('address', models.CharField(max_length=30)),
                ('name', models.CharField(max_length=15)),
                ('city', models.CharField(max_length=15)),
                ('state', models.CharField(max_length=15)),
                ('code', models.IntegerField()),
                ('phone1', models.BigIntegerField()),
                ('phone2', models.BigIntegerField()),
                ('phone_number', models.BigIntegerField()),
                ('fees', models.IntegerField()),
                ('profile_img', models.ImageField(upload_to='media1')),
            ],
        ),
        migrations.CreateModel(
            name='Seller',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField()),
                ('address', models.CharField(max_length=30)),
                ('name', models.CharField(max_length=15)),
                ('city', models.CharField(max_length=15)),
                ('state', models.CharField(max_length=15)),
                ('code', models.IntegerField()),
                ('phone1', models.BigIntegerField()),
                ('phone2', models.BigIntegerField()),
                ('phone_number', models.BigIntegerField()),
                ('fees', models.IntegerField()),
                ('profile_img', models.ImageField(upload_to='media1')),
            ],
        ),
    ]
